### ISSUE TITLE
[FEATURE REQUEST] Add import/export functionality

### ISSUE THREAD

**Issue by Polpetta** [lisaparma/NewBaconMonster-SprintPlanning#3]
It would be cool to generate a JSON to be imported later to restore the planner to a desired state. In this way, the JSON could be attached in different sprint planning documents and be more accessible than an screenshot, thus being editable! :grin:

**Comment by lisaparma** [comment]
Added feature in [v.2.0.0](https://github.com/lisaparma/ScrambledEggs-SprintPlanning/tree/v2.0.0)

**Comment by Polpetta** [comment]
:heart:
