### ISSUE TITLE
[FEATURE REQUEST] Add editable sprint date

### ISSUE THREAD

**Issue by Polpetta** [lisaparma/NewBaconMonster-SprintPlanning#4]
I would be cool to have a date field (like the subtitle or whatever you like) that can be edited to put the sprint date! So when we do the 'promesse elettorali' screenshot/export we know the sprint date too

**Comment by lisaparma** [comment]
Added feature in [v.2.0.0](https://github.com/lisaparma/ScrambledEggs-SprintPlanning/tree/v2.0.0)
